# This workflow will update the data.js file with the latest author
# Runs weekly at
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#

name: 'Techtonic CRON job'

# on: workflow_dispatch
on:
  schedule:
    - cron: '0 23 * * 1'

jobs:
  dataSetup:
    name: Get new author

    runs-on: ubuntu-latest
    env:
        CRON_COMMIT_MESSAGE: CRON - Update data.js
        CRON_COMMIT_AUTHOR: CRON

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

        name: Install dependencies
      - run: cd getTechtonicBook && npm i
        name: Fetch new data
      - run: cd getTechtonicBook && npm run fetch --if-present

      - name: GIT Commit Changes
        run: |
            git config --global user.name "${{ env.CRON_COMMIT_AUTHOR }}"
            git config --global user.email "username@users.noreply.github.com"
            git add .
            git commit -m "${{ env.CRON_COMMIT_MESSAGE }}"
            git push



    # permissions:
    #   actions: read
    #   contents: read
    #   security-events: write
