# This workflow will update the data.js file with the latest author
# Runs weekly at
#
# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#

name: 'Get New Author'

on: workflow_dispatch
# on:
#   schedule:
#     - cron: '0 23 * * 1'

jobs:
  dataSetup:
    name: Data Setup

    runs-on: ubuntu-latest
    env:
        CRON_COMMIT_MESSAGE: CRON - Update data.js
        CRON_COMMIT_AUTHOR: CRON

    # TODO : Make artifact and upload to repo
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
      - run: cd getTechtonicBook && npm i
      - run: cd getTechtonicBook && npm run fetch --if-present
      - name: GIT Commit Build Artifacts
        run: |
            git config --global user.name "${{ env.CRON_COMMIT_AUTHOR }}"
            git config --global user.email "username@users.noreply.github.com"
            git commit -a -m "${{ env.CRON_COMMIT_MESSAGE }}"
            git push



    # permissions:
    #   actions: read
    #   contents: read
    #   security-events: write